### PR TITLE
Changed ATTs infrastructure to newest ConfigureEndpointTestExecution

### PR DESCRIPTION
**Pull request by danielmarbach**
Connects to https://github.com/Particular/NServiceBus/pull/3514#issuecomment-189050351

### CODE REVIEW

**Comment by weralabaj** [comment]
I'm looking into it.

**Comment by danielmarbach** [comment]
Did an update

**Comment by weralabaj** [comment]
@danielmarbach when running locally there's a subtle issue 
var transportsOtherThanMsmq = runDescriptors.Where(t => t == Msmq); doesn't actually exclude running tests for Msmq. That doesn't seem to be an issue on TC, however.

**Comment by danielmarbach** [comment]
Hmm... Need to check. The only thing I changed was that I evaluate it for
each run.

On Monday, February 29, 2016, Weronika Łabaj <notifications@github.com>
wrote:

> @danielmarbach <https://github.com/danielmarbach> when running locally
> there's a subtle issue
> var transportsOtherThanMsmq = runDescriptors.Where(t => t == Msmq);
> doesn't actually exclude running tests for Msmq. That doesn't seem to be an
> issue on TC, however.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.SqlServer/pull/169#issuecomment-190268140>
> .
>


-- 
*Don't miss the Async/Await Webinar Series*
*• Learn more <http://go.particular.net/l/27442/2016-02-15/681bjl> →*

**Comment by danielmarbach** [comment]
Ok, @andreasohlund fixed it
https://github.com/Particular/NServiceBus/pull/3527

**Comment by weralabaj** [comment]
Upgraded packages and all tests pass.

**Pull request merged**
