### PR TITLE
Complete the scope in the queue peeker and then delay if no messages found

### LINKED ISSUE #654: Flooded logging when SQL connectivity is intermitant
During SQL patching we occasionally get a flood of logging with  2  errors 

## SQL Peek operation failed

```
System.Transactions.TransactionInDoubtException: The transaction is in doubt. ---> System.Data.SqlClient.SqlException: Execution Timeout Expired. The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: The wait operation timed out
--- End of inner exception stack trace --- 
at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) 
at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) 
at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) 
at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj) 
at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest) 
at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest) at System.Data.SqlClient.SqlDelegatedTransaction.SinglePhaseCommit(SinglePhaseEnlistment enlistment)
--- End of inner exception stack trace --- 
at System.Transactions.TransactionStateInDoubt.EndCommit(InternalTransaction tx) 
at System.Transactions.CommittableTransaction.Commit() 
at System.Transactions.TransactionScope.InternalDispose() 
at System.Transactions.TransactionScope.Dispose() 
at NServiceBus.Transport.SQLServer.QueuePeeker.<Peek>d__1.MoveNext()
```

## Exception thrown while performing cancellation
```
System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=10220; handshake=4790;  ---> System.ComponentModel.Win32Exception (258): The wait operation timed out   
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)   
at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)   
at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)\r\n   
at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)   
at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---   
at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at NServiceBus.Transport.SQLServer.SqlConnectionFactory.OpenNewConnection()   
at NServiceBus.Transport.SQLServer.DelayedMessageHandler.MoveMaturedDelayedMessages()
```

## State

net48

```
    <PackageReference Include="NServiceBus" Version="7.2.0" />
    <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="2.2.0" />
    <PackageReference Include="NServiceBus.Persistence.Sql" Version="4.6.1" />
    <PackageReference Include="NServiceBus.SqlServer" Version="4.3.1" />
```
I know we are using an older versions, but i could not see anything in the recent release notes that would address this?

## Critical error

is currently

```
	string fatalMessage = "The following critical error was encountered:\n" + context.get_Error() + "\nProcess is shutting down.";
		Log.Fatal(context.get_Exception(), fatalMessage);
		Log.CloseAndFlush();
		Environment.FailFast(fatalMessage, context.get_Exception());
		return Task.CompletedTask;
```

and when u run locally, and stop sql while running, the critical error is correctly hit and the endpoint shits down

SQL Peek operation failed
Exception thrown while performing cancellation

### PR DESCRIPTION
**Pull request by danielmarbach**
Closes #654

### CODE REVIEW

**Review by tmasternak — APPROVED** [review]

**Comment by SimonCropp** [comment]
shouldnt 

```

circuitBreaker.Success();

if (messageCount == 0)
{
    if (Logger.IsDebugEnabled)
    {
        Logger.Debug($"Input queue empty. Next peek operation will be delayed for {settings.Delay}.");
    }

    await Task.Delay(settings.Delay, cancellationToken).ConfigureAwait(false);
}

be outside the try catch?

**Comment by SimonCropp** [comment]
i also have a question about a scenario.

so peek is called from here 

```
async Task InnerProcessMessages()
{
    while (!cancellationTokenSource.IsCancellationRequested)
    {
        var messageCount = await queuePeeker.Peek(inputQueue, peekCircuitBreaker, cancellationToken).ConfigureAwait(false);

        if (messageCount == 0)
        {
            continue;
        }

        if (cancellationTokenSource.IsCancellationRequested)
        {
            return;
        }

        // We cannot dispose this token source because of potential race conditions of concurrent receives
        var loopCancellationTokenSource = new CancellationTokenSource();

        // If the receive circuit breaker is triggered start only one message processing task at a time.
        var maximumConcurrentReceives = receiveCircuitBreaker.Triggered ? 1 : messageCount;

        for (var i = 0; i < maximumConcurrentReceives; i++)
        {
            if (loopCancellationTokenSource.Token.IsCancellationRequested)
            {
                break;
            }

            await concurrencyLimiter.WaitAsync(cancellationToken).ConfigureAwait(false);

            var receiveTask = InnerReceive(loopCancellationTokenSource);
            runningReceiveTasks.TryAdd(receiveTask, receiveTask);

            receiveTask.ContinueWith((t, state) =>
            {
                var receiveTasks = (ConcurrentDictionary<Task, Task>)state;
                receiveTasks.TryRemove(t, out _);
            }, runningReceiveTasks, TaskContinuationOptions.ExecuteSynchronously)
            .Ignore();
        }
    }
}
```

so in our scenario the TryPeek can succeed and the transaction fails to commit. this can still happen with your change. so messageCount != 0 so Peek will not delay

so then we hit `InnerProcessMessages`. `receiveCircuitBreaker.Triggered` will be true so `maximumConcurrentReceives` will be 1. so when we still perform a `InnerReceive` with no delay, even though we had SQL connectivity issues. and in fact `InnerReceive` will likely fall through to hitting `receiveCircuitBreaker.Failure()`, effectively causing two circuit breaker failures for one message receive attemp

is that expected. i would have assume if InnerProcessMessages fails to interact with sql, it should not proceed happily with nor delay?

**Comment by danielmarbach** [comment]
Thanks, @SimonCropp for the follow-up. I now see what you are talking about. I got a bit mislead by the log statements you showed but after rereading the previous issue and these further explanations I have a way to move forward with this

**Comment by SimonCropp** [comment]
@danielmarbach yeah i think the log statements are a side effect several steps away from the real issue.

**Comment by SimonCropp** [comment]
but i think pull request is definitely an improvement. perhaps even worth merging before further changes?

**Comment by danielmarbach** [comment]
While looking at the code a found a few oddities that I also want to fix. Happy to merge this as is but I think we should then properly disconnect it from the issue. I'll keep you posted

**Review by lailabougria — APPROVED** [review]

**Pull request merged**
