### PR TITLE
Changing Throws to ThrowsAsync

### PR DESCRIPTION
**Pull request by tmasternak**

### CODE REVIEW

**Comment by SimonCropp** [comment]
@tmasternak did i miss this one?

**Comment by tmasternak** [comment]
@SimonCropp not your fault. Current `TC` setup is far from perfect. The build status does not report the ATT results. See #236.

**Comment by tmasternak** [comment]
@Particular/sqlserver-transport-maintainers this is green. Ready to merge.

**Comment by SimonCropp** [comment]
@MarcinHoppe i think u forgot to delete the branch

**Comment by MarcinHoppe** [comment]
@SimonCropp done.

**Pull request merged**
