### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by bording**
This moves the project over to using the new Particular.Packaging package, and cleans up a few other things related to moving to the new project format.

### CODE REVIEW

**Comment by bording** [comment]
Ran the build a couple times, but I'm seeing some failures, which should be unrelated to any changes I've made here AFAIK.

**Comment by MarcinHoppe** [comment]
@Particular/sqlserver-transport-maintainers The PR looks good to me. I will merge it when the build is green.

**Comment by bording** [comment]
@Particular/sqlserver-transport-maintainers This PR still needs to be merged, but I'm still seeing some test failures that don't appear to be related to any of the changes I've made, so these need to be investigated.

**Comment by MarcinHoppe** [comment]
@bording The change looks good and test failures are not related. Merging.

**Pull request merged**
