### PR TITLE
add DictionarySerializer with DataContractJsonSerializer

### PR DESCRIPTION
**Pull request by SimonCropp**
@SzymonPobiega @tmasternak 

rather than ilmerging a 500K dll in the below how about using a DataContractJsonSerializer?
https://github.com/Particular/NServiceBus.SqlServer/pull/150
https://github.com/Particular/NServiceBus.SqlServer/pull/151

### CODE REVIEW

**Comment by HEskandari** [comment]
I like it! :+1:

**Comment by tmasternak** [comment]
@SimonCropp I think that argument was the time of serialization. I think that the difference is considerable. /cc: @danielmarbach

**Comment by danielmarbach** [comment]
image

We feeled this matters

**Comment by danielmarbach** [comment]
Just for your reference. We started using `DataContractSerializer` in CustomChecks and Heartbeats. After the performance discussion around SqlServer we decided to go with one way of doing serialization with Json (using JSon.NET) and bite the bullet of the bigger assemblies. How problematic is the size of the assembly anyway in that case? Can you elaborate?

**Comment by SimonCropp** [comment]
in the scope of a a list of headers that are all strings is that performance comparison relevant?

**Comment by tmasternak** [comment]
@SimonCropp I think we can't answer that without doing tests.

**Comment by danielmarbach** [comment]
I agree with @tmasternak let's measure it.

**Comment by tmasternak** [comment]
@SimonCropp @danielmarbach I'll make measurements and post it here.

**Comment by SimonCropp** [comment]
@danielmarbach scratch the the perf testing. turns out DataContractJsonSerializer  and newtonsoft dont serialize a dictionary the same.

**Comment by SimonCropp** [comment]
Json.net

`{"foo":"bar"}`

DataContractJsonSerializer
 
`[{"Key":"foo","Value":"bar"}]`

**Comment by tmasternak** [comment]
http://stackoverflow.com/questions/4559991/any-way-to-make-datacontractjsonserializer-serialize-dictionaries-properly

**Comment by tmasternak** [comment]
Ok let's make a step back here. Why is 500K so bad?

**Comment by SimonCropp** [comment]
UseSimpleDictionaryFormat worked

**Comment by danielmarbach** [comment]
@SimonCropp you can tweak it. We already use the emit option in the heartbeats https://github.com/Particular/ServiceControl.Plugin.Nsb6.Heartbeat/commit/93a892cec717eef7a3a017670a7e6a9fbc7f18a3#diff-f2f02cdc09cfc9465ca59cfa12954370R32

**Comment by tmasternak** [comment]
Here are test results:

 | Assembly Size | WireCompat | Header De/Serialization | Message Delivery Snd/Rcv
------------ | -------------  | -------------  | -------------  | ------------- 
DataContractJsonSerializer | 62K + 0 | OK | S: 5660 ms  D: 16766 ms | S: 8000 msg/s R: 2000 msg/s S+R: 4000 msg/s, 850 msg/s
Json.Net |  62K + 500K | OK | S: 1851 ms D: 2770 ms | S: 8000 msg/s  R: 2000 msg/s S+R: 4000 msg/s, 1000 msg/s

3rd column -  shows times for serializing [S] and deserializing [D] sample Dictionary<string, string> for 100000 times
4th column -  shows throughput with only sender sending messages [S], only receiver receiving messages [R], and for sender and receiver running at the same time [S+R]

On my machine there is a difference in serialization/deserialization proces but there is no performance degradation when it comes to message throughput (probably because it is I/O bound).

I summary I propose (after syncing with @danielmarbach) to go with `DataContractJsonSerializer` and if in the future we see performance problems due to header serialization we can provide extension method for advanced users. 

/cc: @SimonCropp

**Comment by SimonCropp** [comment]
Do we want to go with a different default encoding?

**Comment by Scooletz** [comment]
@tmasternak Have you tried using [Jil](https://github.com/kevin-montrose/Jil)? If performance matters, there's nothing faster and more `low-alloc` in .NET world then this.

**Comment by SzymonPobiega** [comment]
IMO a binary writer and type-length-value approach would be best but unfortunately not backwards wire-compatible. I think we are stuck with JSON :(

**Comment by SimonCropp** [comment]
closing this one. did a clen PR here https://github.com/Particular/NServiceBus.SqlServer/pull/153

**Pull request closed without merging**
