### PR TITLE
Move TryReceive up the inheritance chain.

### PR DESCRIPTION
**Pull request by SzymonPobiega**

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/sqlserver-transport-maintainers please review. This does not change any functionality, just moves code around to a common place.

**Comment by SzymonPobiega** [comment]
The acceptance tests are failing due to some issues on the build server. Please review anyway.

**Comment by MarcinHoppe** [comment]
LGTM, besides those pesky tests.

**Comment by MarcinHoppe** [comment]
I marked the build as successful (SQL Server login problems on build agents seem to haunt us again). Merging.

**Pull request merged**
