### PR TITLE
Removes references to NHibernate persistence

### PR DESCRIPTION
**Pull request by SzymonPobiega**
In order to not block V7-compatible release.

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
How are we going to verify that we're not escalating in the future without this test?

**Comment by SimonCropp** [comment]
@MarcinHoppe 

> How are we going to verify that we're not escalating in the future without this test?

i think we pull that into a diff repo+sln the same way we have the wire compat tests?

**Comment by MarcinHoppe** [comment]
Wire compat tests recently travelled exactly the opposite route: #353 and are now hosted in this repo.

**Comment by SzymonPobiega** [comment]
I think that breaking this so unlikely that a proper sample would be enough. We do smoke testing via samples before releases anyway.

**Comment by MarcinHoppe** [comment]
I beg to disagree with this:

> I think that breaking this so unlikely

The code around transactions, especially in the transports, was quite tricky to write. I'd prefer to have the safeguard of an automated test to cover this non-trivial guarantee that we give to people using SQL Server only.

**Comment by SzymonPobiega** [comment]
So the alternative would be to add references to NH and SQL persistences in the compat test facades. This way we can have a compat tests that verifies it. Since facades are version-specific, we will just skip the NH in the SQL 4 facade.

**Comment by MarcinHoppe** [comment]
👍

**Comment by SimonCropp** [comment]
@MarcinHoppe 

> Wire compat tests recently travelled exactly the opposite route: #353 and are now hosted in this repo

yes and if you remember i argued against that because it would cause problems long term

**Comment by MarcinHoppe** [comment]
I recall there were arguments both ways. So far I have not heard it is causing problems so we might give this direct a benefit of a doubt and see if it causes pain down the road.

@Particular/sqlserver-transport-maintainers Thoughts?

**Comment by SzymonPobiega** [comment]
I've added two integration tests projects for SQL and NH persistences that verify the escalation. When we switch to V7 with SQL transport develop then we'll remove the NH tests untill NH has a V7 compatible release. Does this sound OK?

**Comment by MarcinHoppe** [comment]
Sounds like a workable plan. I'll merge when the build is green.

**Pull request merged**
