### PR TITLE
Hotfix 3.1.3

### PR DESCRIPTION
**Pull request by MarcinHoppe**

### CODE REVIEW

**Comment by MarcinHoppe** [comment]
@jmezach This is the new PR with your commit cherry-picked.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe hotfix to develop?

**Comment by MarcinHoppe** [comment]
@SzymonPobiega Good catch. I am also fixing an inspection on this branch.

**Comment by jmezach** [comment]
@MarcinHoppe What is the status of this PR? Looks like tests are failing, but I can't see why.

**Comment by MarcinHoppe** [comment]
@jmezach These test failures do not look related to your changes, I am looking into them. I will drive this issue internally so that we could release it.

**Pull request merged**
