### PR TITLE
Updated to Core Rc1

### PR DESCRIPTION
**Pull request by tmasternak**
@SzymonPobiega can you have a look?

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
Why is it WIP?

**Comment by SzymonPobiega** [comment]
I mean, it is green so I would merge it. I won't go through 272 files ;-)

**Comment by tmasternak** [comment]
I guess we colud merge it.

01.09.2016 7:41 PM "Szymon Pobiega" <notifications@github.com> napisał(a):

**Comment by SzymonPobiega** [comment]
One acceptance test failed, re-running.

**Comment by SzymonPobiega** [comment]
Another "random" fail. Something is off...

**Pull request merged**
