### PR TITLE
make CreateDelayedMessageStoreText public

### PR DESCRIPTION
**Pull request by SimonCropp**
so it can be consumed for scripting purposes

### CODE REVIEW

**Comment by SimonCropp** [comment]
should remove the private here https://github.com/Particular/docs.particular.net/blob/master/Snippets/SqlTransport/SqlTransport_4/ScriptWriter.cs#L28

will mean a docs update will catch if something similar happens again.

**Comment by SzymonPobiega** [comment]
Thanks. Can you also ack the API change?

**Comment by SimonCropp** [comment]
done

**Comment by SzymonPobiega** [comment]
ooops. Needs rebase after I merged that other PR

**Comment by SimonCropp** [comment]
done

**Pull request merged**
