### PR TITLE
Fix handling of reply address

### PR DESCRIPTION
**Pull request by SzymonPobiega**
Fixed the problem with SC where the ReplyTo header is corrupted when using V6 multi-schema feature.

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
Wrong target.

**Comment by SzymonPobiega** [comment]
To be cherry-picked to a hotfix branch when reviewed.

**Comment by SzymonPobiega** [comment]
@tmasternak @MarcinHoppe @mikeminutillo this is meant to solve the SC problem. It won't solve the problem with stripping the schema info from the retry destination though.

**Comment by SzymonPobiega** [comment]
@MarcinHoppe release as 2.2.5?

**Comment by MarcinHoppe** [comment]
@SzymonPobiega 👍

**Comment by SzymonPobiega** [comment]
Replaced by #349 that is a proper hotfix.

**Comment by SimonCropp** [comment]
@SzymonPobiega should the branch be deleted?

**Pull request closed without merging**
