### PR TITLE
[WIP] Update NServiceBus 6.1.0

### PR DESCRIPTION
**Pull request by danielmarbach**
Relates to https://github.com/Particular/NServiceBus/pull/4377

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Particular/sqlserver-transport-maintainers see

**Comment by MarcinHoppe** [comment]
@danielmarbach Is this just version bump + ATTs? I can't see any changes in transport code...

**Comment by danielmarbach** [comment]
@MarcinHoppe correct. The ATT framework has a few optimizations contained and a breaking change around IConfigureTestExecution

**Comment by MarcinHoppe** [comment]
Thanks for the PR @danielmarbach. We'll act on it once 6.1 is available.

**Comment by timbussmann** [comment]
@Particular/sqlserver-transport-maintainers 6.1 is now officially released. Feel free to pick up this PR and update it to the final 6.1 package. It's up to you whether you decide to only update the test projects or if you update the main projects build dependency to 6.1 too. In case of the second option, please be careful to update nuspec dependencies only if you make use of newly available 6.1 APIs.

**Comment by MarcinHoppe** [comment]
@danielmarbach Do we need to drop this PR in favor of a new one with updated acceptance test source packages?

**Comment by danielmarbach** [comment]
@MarcinHoppe I updated the PRs usually and did the necessary changes but up to you what makes most sense

**Comment by MarcinHoppe** [comment]
Closing in favor of #334

**Pull request closed without merging**
