### PR TITLE
Cannot pass Timeout.InfiniteTimeSpan

### PR DESCRIPTION
**Pull request by ramonsmits**
Disable the native delayed delivery processing by passing an infinite timeout value.

### CODE REVIEW

**Comment by mauroservienti** [comment]
@ramonsmits is this still relevant?

**Comment by mauroservienti** [comment]
@ramonsmits can you also please describe a use case for this?

**Comment by WilliamBZA** [comment]
Replaced by https://github.com/Particular/NServiceBus.SqlServer/pull/721

**Comment by ramonsmits** [comment]
Reopening as this is needed when there are multiple instances.

**Comment by WilliamBZA** [comment]
> Customers can also achieve something similar by changing the timeout check interval.

**Pull request closed without merging**
