### PR TITLE
Abort using cancellationtoken

### PR DESCRIPTION
**Pull request by andreasohlund**
Waiting for the core pull

### CODE REVIEW

**Comment by andreasohlund** [comment]
@tmasternak please do a preliminary review

**Comment by tmasternak** [comment]
I think we should pass the token to the TableBasedQueue operations as well [e.g.](https://github.com/Particular/NServiceBus.SqlServer/blob/abort-using-cancellationtoken/src/NServiceBus.SqlServer/Receiving/ReceiveWithNativeTransaction.cs#L25)

**Comment by weralabaj** [comment]
Is it waiting for anything?

**Comment by weralabaj** [comment]
Btw is it using the latest core version or we need to do upgrade in another PR?

**Comment by tmasternak** [comment]
I think that it was a part of bigger issues around supporting cancellation token. I think that other transports are not validated yet and we are waiting for that. When that's done pull to core will be done and we will be able to merge what @andreasohlund did. @andreasohlund (am I getting it right?)

**Comment by andreasohlund** [comment]
I will hand this off to @Scooletz tomorrow

**Comment by Scooletz** [comment]
@tmasternak I've just pushed the latest version of the PR to github. I won't be merged to core till I don't go with Rabbit transport and align all of them. Do you want me to go with that and check the alignment to the recent version, or do you want to do it on your own? :) I'm ok with the first - the more I read now, the more I know in my first days :)

**Comment by Scooletz** [comment]
Just a note after discussion with @tmasternak  I'll make that aligned to the PR on core.

**Comment by Scooletz** [comment]
@weralabaj @tmasternak Rebased on top of develop with the core package version updated. Can you merge that to the transport after reviewing it?

**Pull request merged**
