### PR TITLE
Callback using routing

### PR DESCRIPTION
**Pull request by SzymonPobiega**
* Adds handling of legacy callback headers
 * Updates to latest core

### CODE REVIEW

**Comment by SzymonPobiega** [comment]
@Particular/transport-maintainers please review.

**Comment by SzymonPobiega** [comment]
@weralabaj pushed the changes.

**Comment by weralabaj** [comment]
@tmasternak can I merge?

**Comment by tmasternak** [comment]
:+1:

**Comment by weralabaj** [comment]
One thing I forgot - we probably should update the doco and ProdTests to capture this change, right?

**Comment by tmasternak** [comment]
:+1: for doco. I'm not sure about ProdTests I think that it's probably not worth touching them until we have  instance-id based callbacks in SqlTransport.

**Comment by weralabaj** [comment]
Ok new issue here https://github.com/Particular/docs.particular.net/issues/1193. @SzymonPobiega can you add other PRs that relate to it?

**Comment by tmasternak** [comment]
@weralabaj actually I think there is not that much to put in docs yet as well. Apart from SqlTransport v3 is compatible with callbacks in previous version when it's on the receiving side.

**Pull request merged**
