### PR TITLE
WIP: Compatibility Tests

### PR DESCRIPTION
**Pull request by petersgiles**
A working branch for developing tests

https://github.com/Particular/NServiceBus.SqlServer/issues/110

@weralabaj I figured we could work in here

### CODE REVIEW

**Comment by weralabaj** [comment]
@petersgiles Cool, what are you working on?

**Comment by petersgiles** [comment]
I was looking at service control compatibility. It's weird though. It seems that we've withdrawn multiple database support for NServiceBus.SqlServer (which Service Control doesn't support).

Also the tests that are currently in develop are all coming up red so I'm trying to work out what it going on there. Other than that I guess I'm going to start at the top and work down the list.

**Comment by petersgiles** [comment]
Hmm the ServiceControl test I did probably doesn't belong in this repo maybe https://github.com/Particular/ProductionTests

**Comment by weralabaj** [comment]
@petersgiles The support for multi-db in SqlTransport v3 (Core v6) is not removed, it's just not implemented yet ;)
It's WIP - /cc @mauroservienti @justabitofcode 

Regarding ServiceControl - you're talking about the issue with current implementation (desk case) or future plans? Either way would be good to sync!

**Comment by petersgiles** [comment]
@SimonCropp was saying that a test in this repo for the configuration of SC is kind of daft (not his exact words) there's another mechanism for doing it when the product is built. I need him to repeat what it was because there were a lot of words about stuff i'm not familiar with

**Comment by weralabaj** [comment]
OK, please, let us know how you decided to go about this then.

**Comment by mauroservienti** [comment]
* I agree that we must test all the things that can interact/run in the ServiceControl process even if they are not specifically developed for ServiceControl
* I also thing that these tests don't belong here.

**Comment by tmasternak** [comment]
@petersgiles any updates on that?

**Comment by petersgiles** [comment]
@tmasternak well my feeling is that the tests should be moved to the core

**Comment by SimonCropp** [comment]
How can tests that rely on sql transport be in the core?

**Comment by tmasternak** [comment]
Do we have any SC integration tests?

**Comment by mauroservienti** [comment]
@tmasternak not that I'm aware of. @johnsimons is there a way to run integration tests that involves an endpoint and SC?

**Comment by petersgiles** [comment]
@SimonCropp many of these are actually NServiceBus integration tests and any transport would do. The file system transport that @andreasohlund was talking about putting into the core would be as appropriate. That's why I was thinking of the core.

If we are testing transport configuration then I would put that test in a transport solution.

**Comment by SimonCropp** [comment]
@petersgiles i said it didnt make sense to have this in the sql server repo since it is testing multiple versions. a given point in a repo is a single instance. so u need to have it somewhere else where, gradually, more versions can be added to the compat matrix.

**Comment by weralabaj** [comment]
@petersgiles Would it make sense to create SC tests in https://github.com/Particular/ProductionTests/ (see others here https://github.com/Particular/ProductionTests/tree/master/src)? Then we wouldn't limit it to the specific transport and its version.

**Comment by petersgiles** [comment]
@weralabaj yes that makes sense to me

**Comment by tmasternak** [comment]
Closing this one. I've opened issue in ProductionTests

**Comment by weralabaj** [comment]
Btw @petersgiles if we could help with setting it up (me, Tomasz or Alessandro) let us know!

**Comment by petersgiles** [comment]
go for it

**Pull request closed without merging**
